
const serverPort = 3003;
const mqttServer = 'mqtt://192.168.22.5'

const menus = {                                                                                                                                                                                                                                                                                                                
  menu: [                                                                                                                                                                                                                                                                                                                      
    { icon: "mdi-view-dashboard", text: "Dashboard", href: "/" },                                                                                                                                                                                                                                                              
    { icon: "mdi-lock", text: "Portal", href: "portal" },                                                                                                                                                                                                                                                                      
    { icon: "mdi-lan", text: "WOL", href: "wol" },                                                                                                                                                                                                                                                                             
    { icon: 'mdi-cloud', text: 'Nextcloud', href: 'http://nextcloud.nuc3.muh' }                                                                                                                                                                                                                                                
  ],                                                                                                                                                                                                                                                                                                                           
};                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                               
const portals = {                                                                                                                                                                                                                                                                                                              
  portals: [                                                                                                                                                                                                                                                                                                                   
    //{ id: "1", name: "HD", state: 1, tstamp: "1682600411"}                                                                                                                                                                                                                                                                   
    {                                                                                                                                                                                                                                                                                                                          
      id: 4, pin: 25,                                                                                                                                                                                                                                                                                                          
      name: "housedoor", name_short: "hd", name_long: "Haustür",                                                                                                                                                                                                                                                               
      state_name: ["CLOSED", "OPENED"]                                                                                                                                                                                                                                                                                         
    },                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                          
      id: 5, pin: 8, pin_lock: 16, pin_unlock: 20, pin_hold: 500, lock_timer: false,                                                                                                                                                                                                                                           
      name: "housedoorlock", name_short: "hdl", name_long: "Haustür Riegel",                                                                                                                                                                                                                                                   
      state_name: ["LOCKED", "UNLOCKED"]                                                                                                                                                                                                                                                                                       
    },                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                          
      id: 2, pin: 13,                                                                                                                                                                                                                                                                                                          
      name: "garagedoor", name_short: "gd", name_long: "Garagentür",                                                                                                                                                                                                                                                           
      state_name: ["CLOSED", "OPENED"]                                                                                                                                                                                                                                                                                         
    },                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                          
      id: 3, pin: 6, pin_lock: 19, pin_unlock: 26, pin_hold: 500, led: false,                                                                                                                                                                                                                                                  
      name: "garagedoorlock", name_short: "gdl", name_long: "Garagentür Riegel",                                                                                                                                                                                                                                               
      state_name: ["LOCKED", "UNLOCKED"]                                                                                                                                                                                                                                                                                       
    },                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                          
      id: 1, pin: 5, pin_move: 12, pin_hold: 400, led: false,                                                                                                                                                                                                                                                                  
      name: "garage", name_short: "g", name_long: "Garage",                                                                                                                                                                                                                                                                    
      state_name: ["CLOSED", "OPENED"]                                                                                                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                                                                                                          
  ],                                                                                                                                                                                                                                                                                                                           
};                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                               
// Define the hosts object                                                                                                                                                                                                                                                                                                     
const hosts = {                                                                                                                                                                                                                                                                                                                
  hosts: [                                                                                                                                                                                                                                                                                                                     
    { name: "google.com", port: "80" },                                                                                                                                                                                                                                                                                        
  ],                                                                                                                                                                                                                                                                                                                           
}; 

export { serverPort, mqttServer, menus, portals, hosts }
